#pragma once

#import "../BridgeTypes.h"

extern HookEntry gHooks[128];
extern int gHookCount;
extern bool gTriedKeyboardConnect;
extern bool gMouseConnected;
extern unsigned int gMouseConnectAttempts;
extern id gKeyboardInput;
extern id gMouseInput;
extern id gLastController;
extern id gMouseButtons[3];
extern id gScrollInput;
extern id gScrollXAxis;
extern id gScrollYAxis;
extern void (^gKeyChangedHandler)(id keyboardInput, id key, unsigned short keyCode, BOOL pressed);
extern void (^gMouseMovedHandler)(id mouseInput, float deltaX, float deltaY);
extern void (^gMousePressedHandlers[3])(id buttonInput, float value, BOOL pressed);
extern void (^gMouseValueHandlers[3])(id buttonInput, float value, BOOL pressed);
extern void (^gMouseTouchedHandlers[3])(id buttonInput, float value, BOOL pressed, BOOL touched);
extern void (^gScrollChangedHandler)(id scrollInput, float xValue, float yValue);
extern void (^gScrollXAxisChangedHandler)(id axisInput, float value);
extern void (^gScrollYAxisChangedHandler)(id axisInput, float value);
extern bool gMouseButtonStates[3];
extern bool gMouseButtonSuppressedByBridgeUI[3];
extern float gScrollXValue;
extern float gScrollYValue;
extern bool gPressedKeys[UINT16_MAX + 1];
extern bool gSuppressedKeys[UINT16_MAX + 1];
extern bool gMenuSuppressedKeys[UINT16_MAX + 1];
extern bool gMissingMacKeyLogged[UINT16_MAX + 1];
extern unsigned short gActiveKeyCodes[256];
extern unsigned int gActiveKeyCount;
extern dispatch_source_t gPollTimer;
extern dispatch_source_t gMouseRetryTimer;
extern dispatch_source_t gSyntheticMouseTimer;
extern dispatch_source_t gControllerDiscoveryTimer;
extern CGEventSourceKeyStateFn gCGEventSourceKeyState;
extern CGGetLastMouseDeltaFn gCGGetLastMouseDelta;
extern CGEventSourceCounterForEventTypeFn gCGEventSourceCounterForEventType;
extern CGEventSourceButtonStateFn gCGEventSourceButtonState;
extern CGEventTapCreateFn gCGEventTapCreate;
extern CGEventGetIntegerValueFieldFn gCGEventGetIntegerValueField;
extern CGEventTapEnableFn gCGEventTapEnable;
extern CGAssociateMouseAndMouseCursorPositionFn gCGAssociateMouseAndMouseCursorPosition;
extern CGDisplayHideCursorFn gCGDisplayHideCursor;
extern CGDisplayShowCursorFn gCGDisplayShowCursor;
extern CGWarpMouseCursorPositionFn gCGWarpMouseCursorPosition;
extern CGMainDisplayIDFn gCGMainDisplayID;
extern CGDisplayBoundsFn gCGDisplayBounds;
extern bool gTriedResolveKeyState;
extern bool gTriedResolveMouseFunctions;
extern bool gTriedResolveScrollFunctions;
extern bool gTriedResolvePointerCaptureFunctions;
extern bool gKeyStateUnavailableLogged;
extern bool gMouseFunctionsUnavailableLogged;
extern bool gScrollFunctionsUnavailableLogged;
extern bool gPointerCaptureFunctionsUnavailableLogged;
extern bool gPointerLockWanted;
extern bool gPointerLockInhibited;
extern unsigned short gPointerLockReleaseKeyCode;
extern bool gPointerLockRearmAllowedByToggle;
extern bool gPointerLockRearmAllowedByMouseClick;
extern bool gPointerCaptureActive;
extern bool gPointerCursorDetached;
extern bool gPointerCursorHidden;
extern bool gTextInputActive;
extern bool gClearingPointerLock;
extern bool gPointerLockReturnLogged;
extern bool gDropNextMouseDeltaAfterPointerLock;
extern bool gDropInitialSyntheticMouseDelta;
extern bool gPointerRegionNilLogged;
extern bool gPointerRegionLogged;
extern bool gTouchSuppressionLogged;
extern bool gPointerRearmBlockedLogged;
extern bool gNativePrefersPointerLockedLogged;
extern BOOL gNativePrefersPointerLockedLastValue;
extern bool gMouseLookAllowed;
extern bool gMouseLookAllowedLogged;
extern bool gNativeMouseMovementLogged;
extern bool gSyntheticMouseMovementSuppressedLogged;
extern bool gMouseCountersInitialized;
extern uint32_t gMouseMoveCounters[4];
extern uint64_t gLastNativeMouseMoveUsec;
extern CFMachPortRef gScrollEventTap;
extern CFRunLoopSourceRef gScrollEventTapSource;
extern unsigned int gControllerDiscoveryAttempts;
extern id gBridgeMenuOverlayView;
extern id gBridgeHUDToggleButton;
extern id gBridgeHUDSprintStatusButton;
extern id gBridgeHUDSettingsButton;
extern id gBridgeSprintModeButton;
extern id gBridgeSprintKeyButton;
extern bool gBridgeMenuVisible;
extern bool gBridgeMenuRestoreMouseLookOnHide;
extern bool gBridgeMenuCapturingSprintKey;
extern bool gBridgeHUDEditorActive;
extern BridgeHUDElement gBridgeHUDSelectedElement;
extern bool gBridgeHUDEnabled;
extern bool gBridgeHUDSprintStatusEnabled;
extern double gBridgeHUDSprintX;
extern double gBridgeHUDSprintY;
extern double gBridgeHUDSprintSize;
extern double gBridgeHUDSprintAlpha;
extern BridgeSprintMode gBridgeSprintMode;
extern unsigned short gBridgeSprintKeyCode;
extern bool gBridgeSprintToggleDesired;
extern bool gBridgeSprintToggleHeldInGame;
extern bool gSuppressOriginalPressesBegan;
